### ISSUE TITLE
Question on equation(5) in paper

### ISSUE THREAD

**Issue by lizhenstat** [wangsiwei2010/k-means-filling#1]
Hi, 
    Thanks for your great work for solving k-means clustering problem with missing data.
    I have one question here:
    When optimizing mu with fixed X and H, the paper says "assume the data matrix is complete", 
    how do we initialize X from the missing data in the first step?
    Thanks a lot

**Comment by wangsiwei2010** [comment]
As the paper states, we should initialize the missing values by mean values or first guess. Thanks！

**Comment by lizhenstat** [comment]
@wangsiwei2010  Thanks a lot, sorry about my careless reading!
